### ISSUE TITLE
Hang on Virtual II emulator

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/wizard-replay#1]
Cool project! I tried it out in MAME which worked great, but it hung on Virtual II. Seems to be related to the 80-column firmware? It gets through the select screen, but hangs with a white square in the upper left corner. I wasn't able to find any of the referenced addresses in the code. An instruction trail from V2 is included. It just loops through that section of code endlessly and never starts each game.
![Screen Shot 2023-12-01 at 5 55 52 PM](https://github.com/a2-4am/wizard-replay/assets/34376619/a087e752-cab0-4a28-a92d-89904c59b69a)

**Comment by frankmilliron** [comment]
This only seems to be happening with a //e. Loads fine on a ][+. The first load doesn't seem to be happening, so maybe I was incorrect about it being related to the 80-column firmware.

**Comment by peterferrie** [comment]
That's the slot-scanning code.  Maybe one of the Virtual II cards doesn't
like being pinged.  Please add a save-state so that we have a matching
configuration and I will investigate it.

**Comment by frankmilliron** [comment]
I tried removing all cards and it still wasn't working. Here's a memory dump.
[Mem.bin.zip](https://github.com/a2-4am/wizard-replay/files/13533347/Mem.bin.zip)

**Comment by frankmilliron** [comment]
Here's a dump with no cards installed. The previous was from my "loaded" setup.
[NoCards.bin.zip](https://github.com/a2-4am/wizard-replay/files/13533412/NoCards.bin.zip)

**Comment by frankmilliron** [comment]
It's hanging on slot 3 so maybe I wasn't too far off base.

**Comment by frankmilliron** [comment]
$F6 changes between $C300 and $C35C

**Comment by peterferrie** [comment]
It's failing to find any Disk II card, which it's expecting to be present.  I'll fix this.

**Comment by frankmilliron** [comment]
Can confirm it runs normally if I add a disk II with no drives attached.

**Comment by peterferrie** [comment]
fixed in 7d4206ed2e9924acf3a40cd0707def9bb40f74c1

**Comment by dlxmax** [comment]
EDIT: nvm... built it myself--working great!
Great project. I love this.
@peterferrie Could we please get a release with this fix? Neither of my Apple IIe's have floppy cards. Thanks!

**Comment by peterferrie** [comment]
pferrie.epizy.com/misc/tmp/wizard-replay.zip
@dlxmax  please comment when you have downloaded it.

**Comment by dlxmax** [comment]
@peterferrie Thanks! Though, I think you missed my "edit" comment--I built the current repo on my own and it's working great.

**Comment by peterferrie** [comment]
@dlxmax Okay, that's great too.  I get notifications only for the initial
post.  Edits don't get delivered, so yes, I missed it. :-)

**Comment by roughana** [comment]
Also failing for me on real hardware: Platinum //e with booti
